services:
  db:
    build:
      context: ./order_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "54329:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders"]
      interval: 2s
      timeout: 3s
      retries: 60
    command: ["postgres", "-c", "log_statement=none", "-c", "shared_preload_libraries=pg_stat_statements"]

  order-service:
    build:
      context: ./order-gateway
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: orders
      # Optional: connection string override
      # DATABASE_URL: postgres://postgres:postgres@db:5432/orders?sslmode=disable
      PORT: "8080"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
