services:
  db:
    build: .
    container_name: order_db_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "54329:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders"]
      interval: 2s
      timeout: 3s
      retries: 30
    volumes: []
    command: ["postgres", "-c", "log_statement=none", "-c", "shared_preload_libraries=pg_stat_statements"]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: trading_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
