// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: trading/order/v1/order_service.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderSide int32

const (
	OrderSide_ORDER_SIDE_UNSPECIFIED OrderSide = 0
	OrderSide_ORDER_SIDE_BUY         OrderSide = 1
	OrderSide_ORDER_SIDE_SELL        OrderSide = 2
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "ORDER_SIDE_UNSPECIFIED",
		1: "ORDER_SIDE_BUY",
		2: "ORDER_SIDE_SELL",
	}
	OrderSide_value = map[string]int32{
		"ORDER_SIDE_UNSPECIFIED": 0,
		"ORDER_SIDE_BUY":         1,
		"ORDER_SIDE_SELL":        2,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_trading_order_v1_order_service_proto_enumTypes[0].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_trading_order_v1_order_service_proto_enumTypes[0]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED   OrderType = 0
	OrderType_ORDER_TYPE_MARKET        OrderType = 1
	OrderType_ORDER_TYPE_LIMIT         OrderType = 2
	OrderType_ORDER_TYPE_STOP          OrderType = 3
	OrderType_ORDER_TYPE_STOP_LIMIT    OrderType = 4
	OrderType_ORDER_TYPE_TWAP          OrderType = 5
	OrderType_ORDER_TYPE_DCA           OrderType = 6
	OrderType_ORDER_TYPE_SCALE         OrderType = 7
	OrderType_ORDER_TYPE_TRAILING_STOP OrderType = 8
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_MARKET",
		2: "ORDER_TYPE_LIMIT",
		3: "ORDER_TYPE_STOP",
		4: "ORDER_TYPE_STOP_LIMIT",
		5: "ORDER_TYPE_TWAP",
		6: "ORDER_TYPE_DCA",
		7: "ORDER_TYPE_SCALE",
		8: "ORDER_TYPE_TRAILING_STOP",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED":   0,
		"ORDER_TYPE_MARKET":        1,
		"ORDER_TYPE_LIMIT":         2,
		"ORDER_TYPE_STOP":          3,
		"ORDER_TYPE_STOP_LIMIT":    4,
		"ORDER_TYPE_TWAP":          5,
		"ORDER_TYPE_DCA":           6,
		"ORDER_TYPE_SCALE":         7,
		"ORDER_TYPE_TRAILING_STOP": 8,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_trading_order_v1_order_service_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_trading_order_v1_order_service_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{1}
}

type TimeInForce int32

const (
	TimeInForce_TIME_IN_FORCE_UNSPECIFIED TimeInForce = 0
	TimeInForce_TIME_IN_FORCE_GTC         TimeInForce = 1
	TimeInForce_TIME_IN_FORCE_IOC         TimeInForce = 2
	TimeInForce_TIME_IN_FORCE_FOK         TimeInForce = 3
	TimeInForce_TIME_IN_FORCE_GTD         TimeInForce = 4
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "TIME_IN_FORCE_UNSPECIFIED",
		1: "TIME_IN_FORCE_GTC",
		2: "TIME_IN_FORCE_IOC",
		3: "TIME_IN_FORCE_FOK",
		4: "TIME_IN_FORCE_GTD",
	}
	TimeInForce_value = map[string]int32{
		"TIME_IN_FORCE_UNSPECIFIED": 0,
		"TIME_IN_FORCE_GTC":         1,
		"TIME_IN_FORCE_IOC":         2,
		"TIME_IN_FORCE_FOK":         3,
		"TIME_IN_FORCE_GTD":         4,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_trading_order_v1_order_service_proto_enumTypes[2].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_trading_order_v1_order_service_proto_enumTypes[2]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{2}
}

type MarginMode int32

const (
	MarginMode_MARGIN_MODE_UNSPECIFIED MarginMode = 0
	MarginMode_MARGIN_MODE_CROSS       MarginMode = 1
	MarginMode_MARGIN_MODE_ISOLATED    MarginMode = 2
)

// Enum value maps for MarginMode.
var (
	MarginMode_name = map[int32]string{
		0: "MARGIN_MODE_UNSPECIFIED",
		1: "MARGIN_MODE_CROSS",
		2: "MARGIN_MODE_ISOLATED",
	}
	MarginMode_value = map[string]int32{
		"MARGIN_MODE_UNSPECIFIED": 0,
		"MARGIN_MODE_CROSS":       1,
		"MARGIN_MODE_ISOLATED":    2,
	}
)

func (x MarginMode) Enum() *MarginMode {
	p := new(MarginMode)
	*p = x
	return p
}

func (x MarginMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarginMode) Descriptor() protoreflect.EnumDescriptor {
	return file_trading_order_v1_order_service_proto_enumTypes[3].Descriptor()
}

func (MarginMode) Type() protoreflect.EnumType {
	return &file_trading_order_v1_order_service_proto_enumTypes[3]
}

func (x MarginMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarginMode.Descriptor instead.
func (MarginMode) EnumDescriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{3}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED      OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING          OrderStatus = 1
	OrderStatus_ORDER_STATUS_OPEN             OrderStatus = 2
	OrderStatus_ORDER_STATUS_PARTIALLY_FILLED OrderStatus = 3
	OrderStatus_ORDER_STATUS_FILLED           OrderStatus = 4
	OrderStatus_ORDER_STATUS_CANCELLED        OrderStatus = 5
	OrderStatus_ORDER_STATUS_REJECTED         OrderStatus = 6
	OrderStatus_ORDER_STATUS_EXPIRED          OrderStatus = 7
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_OPEN",
		3: "ORDER_STATUS_PARTIALLY_FILLED",
		4: "ORDER_STATUS_FILLED",
		5: "ORDER_STATUS_CANCELLED",
		6: "ORDER_STATUS_REJECTED",
		7: "ORDER_STATUS_EXPIRED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":      0,
		"ORDER_STATUS_PENDING":          1,
		"ORDER_STATUS_OPEN":             2,
		"ORDER_STATUS_PARTIALLY_FILLED": 3,
		"ORDER_STATUS_FILLED":           4,
		"ORDER_STATUS_CANCELLED":        5,
		"ORDER_STATUS_REJECTED":         6,
		"ORDER_STATUS_EXPIRED":          7,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_trading_order_v1_order_service_proto_enumTypes[4].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_trading_order_v1_order_service_proto_enumTypes[4]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{4}
}

type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED TransactionStatus = 0
	TransactionStatus_TRANSACTION_STATUS_PENDING     TransactionStatus = 1
	TransactionStatus_TRANSACTION_STATUS_CONFIRMED   TransactionStatus = 2
	TransactionStatus_TRANSACTION_STATUS_FAILED      TransactionStatus = 3
	TransactionStatus_TRANSACTION_STATUS_REVERTED    TransactionStatus = 4
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNSPECIFIED",
		1: "TRANSACTION_STATUS_PENDING",
		2: "TRANSACTION_STATUS_CONFIRMED",
		3: "TRANSACTION_STATUS_FAILED",
		4: "TRANSACTION_STATUS_REVERTED",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNSPECIFIED": 0,
		"TRANSACTION_STATUS_PENDING":     1,
		"TRANSACTION_STATUS_CONFIRMED":   2,
		"TRANSACTION_STATUS_FAILED":      3,
		"TRANSACTION_STATUS_REVERTED":    4,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_trading_order_v1_order_service_proto_enumTypes[5].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_trading_order_v1_order_service_proto_enumTypes[5]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{5}
}

type CreateOrderRequest struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	StrategyId           int32                   `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	SourceNetworkId      *wrapperspb.Int32Value  `protobuf:"bytes,2,opt,name=source_network_id,json=sourceNetworkId,proto3" json:"source_network_id,omitempty"`
	DestNetworkId        *wrapperspb.Int32Value  `protobuf:"bytes,3,opt,name=dest_network_id,json=destNetworkId,proto3" json:"dest_network_id,omitempty"`
	AdapterKey           string                  `protobuf:"bytes,4,opt,name=adapter_key,json=adapterKey,proto3" json:"adapter_key,omitempty"`
	IdempotencyKey       string                  `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	AssetInRef           string                  `protobuf:"bytes,6,opt,name=asset_in_ref,json=assetInRef,proto3" json:"asset_in_ref,omitempty"`
	AssetOutRef          string                  `protobuf:"bytes,7,opt,name=asset_out_ref,json=assetOutRef,proto3" json:"asset_out_ref,omitempty"`
	Side                 OrderSide               `protobuf:"varint,8,opt,name=side,proto3,enum=trading.order.v1.OrderSide" json:"side,omitempty"`
	Type                 OrderType               `protobuf:"varint,9,opt,name=type,proto3,enum=trading.order.v1.OrderType" json:"type,omitempty"`
	Tif                  TimeInForce             `protobuf:"varint,10,opt,name=tif,proto3,enum=trading.order.v1.TimeInForce" json:"tif,omitempty"`
	ReduceOnly           bool                    `protobuf:"varint,11,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	PostOnly             bool                    `protobuf:"varint,12,opt,name=post_only,json=postOnly,proto3" json:"post_only,omitempty"`
	Leverage             string                  `protobuf:"bytes,13,opt,name=leverage,proto3" json:"leverage,omitempty"`
	MarginMode           MarginMode              `protobuf:"varint,14,opt,name=margin_mode,json=marginMode,proto3,enum=trading.order.v1.MarginMode" json:"margin_mode,omitempty"`
	AmountIn             string                  `protobuf:"bytes,15,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`
	AmountOutMin         *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=amount_out_min,json=amountOutMin,proto3" json:"amount_out_min,omitempty"`
	LimitPrice           *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	StopPrice            *wrapperspb.StringValue `protobuf:"bytes,18,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	SlippageTolerance    *wrapperspb.StringValue `protobuf:"bytes,19,opt,name=slippage_tolerance,json=slippageTolerance,proto3" json:"slippage_tolerance,omitempty"`
	Tags                 []string                `protobuf:"bytes,20,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata             *structpb.Struct        `protobuf:"bytes,21,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ExecutionPreferences *structpb.Struct        `protobuf:"bytes,22,opt,name=execution_preferences,json=executionPreferences,proto3" json:"execution_preferences,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_trading_order_v1_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_v1_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetStrategyId() int32 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

func (x *CreateOrderRequest) GetSourceNetworkId() *wrapperspb.Int32Value {
	if x != nil {
		return x.SourceNetworkId
	}
	return nil
}

func (x *CreateOrderRequest) GetDestNetworkId() *wrapperspb.Int32Value {
	if x != nil {
		return x.DestNetworkId
	}
	return nil
}

func (x *CreateOrderRequest) GetAdapterKey() string {
	if x != nil {
		return x.AdapterKey
	}
	return ""
}

func (x *CreateOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateOrderRequest) GetAssetInRef() string {
	if x != nil {
		return x.AssetInRef
	}
	return ""
}

func (x *CreateOrderRequest) GetAssetOutRef() string {
	if x != nil {
		return x.AssetOutRef
	}
	return ""
}

func (x *CreateOrderRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetTif() TimeInForce {
	if x != nil {
		return x.Tif
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *CreateOrderRequest) GetPostOnly() bool {
	if x != nil {
		return x.PostOnly
	}
	return false
}

func (x *CreateOrderRequest) GetLeverage() string {
	if x != nil {
		return x.Leverage
	}
	return ""
}

func (x *CreateOrderRequest) GetMarginMode() MarginMode {
	if x != nil {
		return x.MarginMode
	}
	return MarginMode_MARGIN_MODE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *CreateOrderRequest) GetAmountOutMin() *wrapperspb.StringValue {
	if x != nil {
		return x.AmountOutMin
	}
	return nil
}

func (x *CreateOrderRequest) GetLimitPrice() *wrapperspb.StringValue {
	if x != nil {
		return x.LimitPrice
	}
	return nil
}

func (x *CreateOrderRequest) GetStopPrice() *wrapperspb.StringValue {
	if x != nil {
		return x.StopPrice
	}
	return nil
}

func (x *CreateOrderRequest) GetSlippageTolerance() *wrapperspb.StringValue {
	if x != nil {
		return x.SlippageTolerance
	}
	return nil
}

func (x *CreateOrderRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateOrderRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateOrderRequest) GetExecutionPreferences() *structpb.Struct {
	if x != nil {
		return x.ExecutionPreferences
	}
	return nil
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_trading_order_v1_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_v1_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type AddOrderFillRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	OrderId        string                  `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	IdempotencyKey string                  `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	AmountIn       string                  `protobuf:"bytes,3,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`
	AmountOut      string                  `protobuf:"bytes,4,opt,name=amount_out,json=amountOut,proto3" json:"amount_out,omitempty"`
	Price          string                  `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	FeeAmount      *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	FeeAssetRef    *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=fee_asset_ref,json=feeAssetRef,proto3" json:"fee_asset_ref,omitempty"`
	AdapterKey     *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=adapter_key,json=adapterKey,proto3" json:"adapter_key,omitempty"`
	TxHash         []byte                  `protobuf:"bytes,9,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockNumber    *wrapperspb.Int64Value  `protobuf:"bytes,10,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	LogIndex       *wrapperspb.Int32Value  `protobuf:"bytes,11,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	Status         TransactionStatus       `protobuf:"varint,12,opt,name=status,proto3,enum=trading.order.v1.TransactionStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddOrderFillRequest) Reset() {
	*x = AddOrderFillRequest{}
	mi := &file_trading_order_v1_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderFillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderFillRequest) ProtoMessage() {}

func (x *AddOrderFillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_v1_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderFillRequest.ProtoReflect.Descriptor instead.
func (*AddOrderFillRequest) Descriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *AddOrderFillRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AddOrderFillRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *AddOrderFillRequest) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *AddOrderFillRequest) GetAmountOut() string {
	if x != nil {
		return x.AmountOut
	}
	return ""
}

func (x *AddOrderFillRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *AddOrderFillRequest) GetFeeAmount() *wrapperspb.StringValue {
	if x != nil {
		return x.FeeAmount
	}
	return nil
}

func (x *AddOrderFillRequest) GetFeeAssetRef() *wrapperspb.StringValue {
	if x != nil {
		return x.FeeAssetRef
	}
	return nil
}

func (x *AddOrderFillRequest) GetAdapterKey() *wrapperspb.StringValue {
	if x != nil {
		return x.AdapterKey
	}
	return nil
}

func (x *AddOrderFillRequest) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *AddOrderFillRequest) GetBlockNumber() *wrapperspb.Int64Value {
	if x != nil {
		return x.BlockNumber
	}
	return nil
}

func (x *AddOrderFillRequest) GetLogIndex() *wrapperspb.Int32Value {
	if x != nil {
		return x.LogIndex
	}
	return nil
}

func (x *AddOrderFillRequest) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

type AddOrderFillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fill          *OrderFill             `protobuf:"bytes,1,opt,name=fill,proto3" json:"fill,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderFillResponse) Reset() {
	*x = AddOrderFillResponse{}
	mi := &file_trading_order_v1_order_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderFillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderFillResponse) ProtoMessage() {}

func (x *AddOrderFillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_v1_order_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderFillResponse.ProtoReflect.Descriptor instead.
func (*AddOrderFillResponse) Descriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{3}
}

func (x *AddOrderFillResponse) GetFill() *OrderFill {
	if x != nil {
		return x.Fill
	}
	return nil
}

func (x *AddOrderFillResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type UpdateOrderLifecycleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	NewStatus     OrderStatus            `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=trading.order.v1.OrderStatus" json:"new_status,omitempty"`
	TriggeredAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=triggered_at,json=triggeredAt,proto3" json:"triggered_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderLifecycleRequest) Reset() {
	*x = UpdateOrderLifecycleRequest{}
	mi := &file_trading_order_v1_order_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderLifecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderLifecycleRequest) ProtoMessage() {}

func (x *UpdateOrderLifecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_v1_order_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderLifecycleRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderLifecycleRequest) Descriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOrderLifecycleRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderLifecycleRequest) GetNewStatus() OrderStatus {
	if x != nil {
		return x.NewStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *UpdateOrderLifecycleRequest) GetTriggeredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggeredAt
	}
	return nil
}

func (x *UpdateOrderLifecycleRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *UpdateOrderLifecycleRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateOrderLifecycleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderLifecycleResponse) Reset() {
	*x = UpdateOrderLifecycleResponse{}
	mi := &file_trading_order_v1_order_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderLifecycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderLifecycleResponse) ProtoMessage() {}

func (x *UpdateOrderLifecycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_v1_order_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderLifecycleResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderLifecycleResponse) Descriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOrderLifecycleResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_trading_order_v1_order_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_v1_order_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Fills         []*OrderFill           `protobuf:"bytes,2,rep,name=fills,proto3" json:"fills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_trading_order_v1_order_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_v1_order_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *GetOrderResponse) GetFills() []*OrderFill {
	if x != nil {
		return x.Fills
	}
	return nil
}

type ListOrderFillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ExecutedAfter *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=executed_after,json=executedAfter,proto3" json:"executed_after,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     []byte                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderFillsRequest) Reset() {
	*x = ListOrderFillsRequest{}
	mi := &file_trading_order_v1_order_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderFillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderFillsRequest) ProtoMessage() {}

func (x *ListOrderFillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_v1_order_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderFillsRequest.ProtoReflect.Descriptor instead.
func (*ListOrderFillsRequest) Descriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrderFillsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ListOrderFillsRequest) GetExecutedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAfter
	}
	return nil
}

func (x *ListOrderFillsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrderFillsRequest) GetPageToken() []byte {
	if x != nil {
		return x.PageToken
	}
	return nil
}

type ListOrderFillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fills         []*OrderFill           `protobuf:"bytes,1,rep,name=fills,proto3" json:"fills,omitempty"`
	NextPageToken []byte                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderFillsResponse) Reset() {
	*x = ListOrderFillsResponse{}
	mi := &file_trading_order_v1_order_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderFillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderFillsResponse) ProtoMessage() {}

func (x *ListOrderFillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_v1_order_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderFillsResponse.ProtoReflect.Descriptor instead.
func (*ListOrderFillsResponse) Descriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListOrderFillsResponse) GetFills() []*OrderFill {
	if x != nil {
		return x.Fills
	}
	return nil
}

func (x *ListOrderFillsResponse) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

type Order struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	Id                   string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StrategyId           int32                   `protobuf:"varint,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	SourceNetworkId      *wrapperspb.Int32Value  `protobuf:"bytes,3,opt,name=source_network_id,json=sourceNetworkId,proto3" json:"source_network_id,omitempty"`
	DestNetworkId        *wrapperspb.Int32Value  `protobuf:"bytes,4,opt,name=dest_network_id,json=destNetworkId,proto3" json:"dest_network_id,omitempty"`
	AdapterKey           string                  `protobuf:"bytes,5,opt,name=adapter_key,json=adapterKey,proto3" json:"adapter_key,omitempty"`
	IdempotencyKey       string                  `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	AssetInRef           string                  `protobuf:"bytes,7,opt,name=asset_in_ref,json=assetInRef,proto3" json:"asset_in_ref,omitempty"`
	AssetOutRef          string                  `protobuf:"bytes,8,opt,name=asset_out_ref,json=assetOutRef,proto3" json:"asset_out_ref,omitempty"`
	Side                 OrderSide               `protobuf:"varint,9,opt,name=side,proto3,enum=trading.order.v1.OrderSide" json:"side,omitempty"`
	Type                 OrderType               `protobuf:"varint,10,opt,name=type,proto3,enum=trading.order.v1.OrderType" json:"type,omitempty"`
	Tif                  TimeInForce             `protobuf:"varint,11,opt,name=tif,proto3,enum=trading.order.v1.TimeInForce" json:"tif,omitempty"`
	ReduceOnly           bool                    `protobuf:"varint,12,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	PostOnly             bool                    `protobuf:"varint,13,opt,name=post_only,json=postOnly,proto3" json:"post_only,omitempty"`
	Leverage             *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=leverage,proto3" json:"leverage,omitempty"`
	MarginMode           MarginMode              `protobuf:"varint,15,opt,name=margin_mode,json=marginMode,proto3,enum=trading.order.v1.MarginMode" json:"margin_mode,omitempty"`
	AmountIn             string                  `protobuf:"bytes,16,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`
	AmountOutMin         *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=amount_out_min,json=amountOutMin,proto3" json:"amount_out_min,omitempty"`
	FilledAmount         string                  `protobuf:"bytes,18,opt,name=filled_amount,json=filledAmount,proto3" json:"filled_amount,omitempty"`
	LimitPrice           *wrapperspb.StringValue `protobuf:"bytes,19,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	StopPrice            *wrapperspb.StringValue `protobuf:"bytes,20,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	AverageFillPrice     *wrapperspb.StringValue `protobuf:"bytes,21,opt,name=average_fill_price,json=averageFillPrice,proto3" json:"average_fill_price,omitempty"`
	SlippageTolerance    *wrapperspb.StringValue `protobuf:"bytes,22,opt,name=slippage_tolerance,json=slippageTolerance,proto3" json:"slippage_tolerance,omitempty"`
	Status               OrderStatus             `protobuf:"varint,23,opt,name=status,proto3,enum=trading.order.v1.OrderStatus" json:"status,omitempty"`
	Version              int64                   `protobuf:"varint,24,opt,name=version,proto3" json:"version,omitempty"`
	EventVersion         int64                   `protobuf:"varint,25,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	CreatedAt            *timestamppb.Timestamp  `protobuf:"bytes,26,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SubmittedAt          *timestamppb.Timestamp  `protobuf:"bytes,27,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	AckedAt              *timestamppb.Timestamp  `protobuf:"bytes,28,opt,name=acked_at,json=ackedAt,proto3" json:"acked_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp  `protobuf:"bytes,29,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TriggeredAt          *timestamppb.Timestamp  `protobuf:"bytes,30,opt,name=triggered_at,json=triggeredAt,proto3" json:"triggered_at,omitempty"`
	CompletedAt          *timestamppb.Timestamp  `protobuf:"bytes,31,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	ExpiredAt            *timestamppb.Timestamp  `protobuf:"bytes,32,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	CanceledAt           *timestamppb.Timestamp  `protobuf:"bytes,33,opt,name=canceled_at,json=canceledAt,proto3" json:"canceled_at,omitempty"`
	Tags                 []string                `protobuf:"bytes,34,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata             *structpb.Struct        `protobuf:"bytes,35,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ExecutionPreferences *structpb.Struct        `protobuf:"bytes,36,opt,name=execution_preferences,json=executionPreferences,proto3" json:"execution_preferences,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_trading_order_v1_order_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_v1_order_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{10}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetStrategyId() int32 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

func (x *Order) GetSourceNetworkId() *wrapperspb.Int32Value {
	if x != nil {
		return x.SourceNetworkId
	}
	return nil
}

func (x *Order) GetDestNetworkId() *wrapperspb.Int32Value {
	if x != nil {
		return x.DestNetworkId
	}
	return nil
}

func (x *Order) GetAdapterKey() string {
	if x != nil {
		return x.AdapterKey
	}
	return ""
}

func (x *Order) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Order) GetAssetInRef() string {
	if x != nil {
		return x.AssetInRef
	}
	return ""
}

func (x *Order) GetAssetOutRef() string {
	if x != nil {
		return x.AssetOutRef
	}
	return ""
}

func (x *Order) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Order) GetTif() TimeInForce {
	if x != nil {
		return x.Tif
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (x *Order) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *Order) GetPostOnly() bool {
	if x != nil {
		return x.PostOnly
	}
	return false
}

func (x *Order) GetLeverage() *wrapperspb.StringValue {
	if x != nil {
		return x.Leverage
	}
	return nil
}

func (x *Order) GetMarginMode() MarginMode {
	if x != nil {
		return x.MarginMode
	}
	return MarginMode_MARGIN_MODE_UNSPECIFIED
}

func (x *Order) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *Order) GetAmountOutMin() *wrapperspb.StringValue {
	if x != nil {
		return x.AmountOutMin
	}
	return nil
}

func (x *Order) GetFilledAmount() string {
	if x != nil {
		return x.FilledAmount
	}
	return ""
}

func (x *Order) GetLimitPrice() *wrapperspb.StringValue {
	if x != nil {
		return x.LimitPrice
	}
	return nil
}

func (x *Order) GetStopPrice() *wrapperspb.StringValue {
	if x != nil {
		return x.StopPrice
	}
	return nil
}

func (x *Order) GetAverageFillPrice() *wrapperspb.StringValue {
	if x != nil {
		return x.AverageFillPrice
	}
	return nil
}

func (x *Order) GetSlippageTolerance() *wrapperspb.StringValue {
	if x != nil {
		return x.SlippageTolerance
	}
	return nil
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Order) GetEventVersion() int64 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *Order) GetAckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AckedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Order) GetTriggeredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggeredAt
	}
	return nil
}

func (x *Order) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Order) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *Order) GetCanceledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CanceledAt
	}
	return nil
}

func (x *Order) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Order) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Order) GetExecutionPreferences() *structpb.Struct {
	if x != nil {
		return x.ExecutionPreferences
	}
	return nil
}

type OrderFill struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Id             string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId        string                  `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	IdempotencyKey string                  `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	AmountIn       string                  `protobuf:"bytes,4,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`
	AmountOut      string                  `protobuf:"bytes,5,opt,name=amount_out,json=amountOut,proto3" json:"amount_out,omitempty"`
	Price          string                  `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	FeeAmount      *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	FeeAssetRef    *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=fee_asset_ref,json=feeAssetRef,proto3" json:"fee_asset_ref,omitempty"`
	AdapterKey     string                  `protobuf:"bytes,9,opt,name=adapter_key,json=adapterKey,proto3" json:"adapter_key,omitempty"`
	TxHash         []byte                  `protobuf:"bytes,10,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockNumber    *wrapperspb.Int64Value  `protobuf:"bytes,11,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	LogIndex       *wrapperspb.Int32Value  `protobuf:"bytes,12,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	Status         TransactionStatus       `protobuf:"varint,13,opt,name=status,proto3,enum=trading.order.v1.TransactionStatus" json:"status,omitempty"`
	ConfirmedAt    *timestamppb.Timestamp  `protobuf:"bytes,14,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	RevertedAt     *timestamppb.Timestamp  `protobuf:"bytes,15,opt,name=reverted_at,json=revertedAt,proto3" json:"reverted_at,omitempty"`
	ExecutedAt     *timestamppb.Timestamp  `protobuf:"bytes,16,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderFill) Reset() {
	*x = OrderFill{}
	mi := &file_trading_order_v1_order_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFill) ProtoMessage() {}

func (x *OrderFill) ProtoReflect() protoreflect.Message {
	mi := &file_trading_order_v1_order_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFill.ProtoReflect.Descriptor instead.
func (*OrderFill) Descriptor() ([]byte, []int) {
	return file_trading_order_v1_order_service_proto_rawDescGZIP(), []int{11}
}

func (x *OrderFill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderFill) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderFill) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *OrderFill) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *OrderFill) GetAmountOut() string {
	if x != nil {
		return x.AmountOut
	}
	return ""
}

func (x *OrderFill) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OrderFill) GetFeeAmount() *wrapperspb.StringValue {
	if x != nil {
		return x.FeeAmount
	}
	return nil
}

func (x *OrderFill) GetFeeAssetRef() *wrapperspb.StringValue {
	if x != nil {
		return x.FeeAssetRef
	}
	return nil
}

func (x *OrderFill) GetAdapterKey() string {
	if x != nil {
		return x.AdapterKey
	}
	return ""
}

func (x *OrderFill) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *OrderFill) GetBlockNumber() *wrapperspb.Int64Value {
	if x != nil {
		return x.BlockNumber
	}
	return nil
}

func (x *OrderFill) GetLogIndex() *wrapperspb.Int32Value {
	if x != nil {
		return x.LogIndex
	}
	return nil
}

func (x *OrderFill) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *OrderFill) GetConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

func (x *OrderFill) GetRevertedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevertedAt
	}
	return nil
}

func (x *OrderFill) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

var File_trading_order_v1_order_service_proto protoreflect.FileDescriptor

const file_trading_order_v1_order_service_proto_rawDesc = "" +
	"\n" +
	"$trading/order/v1/order_service.proto\x12\x10trading.order.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc0\b\n" +
	"\x12CreateOrderRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x05R\n" +
	"strategyId\x12G\n" +
	"\x11source_network_id\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x0fsourceNetworkId\x12C\n" +
	"\x0fdest_network_id\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\rdestNetworkId\x12\x1f\n" +
	"\vadapter_key\x18\x04 \x01(\tR\n" +
	"adapterKey\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12 \n" +
	"\fasset_in_ref\x18\x06 \x01(\tR\n" +
	"assetInRef\x12\"\n" +
	"\rasset_out_ref\x18\a \x01(\tR\vassetOutRef\x12/\n" +
	"\x04side\x18\b \x01(\x0e2\x1b.trading.order.v1.OrderSideR\x04side\x12/\n" +
	"\x04type\x18\t \x01(\x0e2\x1b.trading.order.v1.OrderTypeR\x04type\x12/\n" +
	"\x03tif\x18\n" +
	" \x01(\x0e2\x1d.trading.order.v1.TimeInForceR\x03tif\x12\x1f\n" +
	"\vreduce_only\x18\v \x01(\bR\n" +
	"reduceOnly\x12\x1b\n" +
	"\tpost_only\x18\f \x01(\bR\bpostOnly\x12\x1a\n" +
	"\bleverage\x18\r \x01(\tR\bleverage\x12=\n" +
	"\vmargin_mode\x18\x0e \x01(\x0e2\x1c.trading.order.v1.MarginModeR\n" +
	"marginMode\x12\x1b\n" +
	"\tamount_in\x18\x0f \x01(\tR\bamountIn\x12B\n" +
	"\x0eamount_out_min\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueR\famountOutMin\x12=\n" +
	"\vlimit_price\x18\x11 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"limitPrice\x12;\n" +
	"\n" +
	"stop_price\x18\x12 \x01(\v2\x1c.google.protobuf.StringValueR\tstopPrice\x12K\n" +
	"\x12slippage_tolerance\x18\x13 \x01(\v2\x1c.google.protobuf.StringValueR\x11slippageTolerance\x12\x12\n" +
	"\x04tags\x18\x14 \x03(\tR\x04tags\x123\n" +
	"\bmetadata\x18\x15 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12L\n" +
	"\x15execution_preferences\x18\x16 \x01(\v2\x17.google.protobuf.StructR\x14executionPreferences\"D\n" +
	"\x13CreateOrderResponse\x12-\n" +
	"\x05order\x18\x01 \x01(\v2\x17.trading.order.v1.OrderR\x05order\"\xb9\x04\n" +
	"\x13AddOrderFillRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x1b\n" +
	"\tamount_in\x18\x03 \x01(\tR\bamountIn\x12\x1d\n" +
	"\n" +
	"amount_out\x18\x04 \x01(\tR\tamountOut\x12\x14\n" +
	"\x05price\x18\x05 \x01(\tR\x05price\x12;\n" +
	"\n" +
	"fee_amount\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\tfeeAmount\x12@\n" +
	"\rfee_asset_ref\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\vfeeAssetRef\x12=\n" +
	"\vadapter_key\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"adapterKey\x12\x17\n" +
	"\atx_hash\x18\t \x01(\fR\x06txHash\x12>\n" +
	"\fblock_number\x18\n" +
	" \x01(\v2\x1b.google.protobuf.Int64ValueR\vblockNumber\x128\n" +
	"\tlog_index\x18\v \x01(\v2\x1b.google.protobuf.Int32ValueR\blogIndex\x12;\n" +
	"\x06status\x18\f \x01(\x0e2#.trading.order.v1.TransactionStatusR\x06status\"v\n" +
	"\x14AddOrderFillResponse\x12/\n" +
	"\x04fill\x18\x01 \x01(\v2\x1b.trading.order.v1.OrderFillR\x04fill\x12-\n" +
	"\x05order\x18\x02 \x01(\v2\x17.trading.order.v1.OrderR\x05order\"\xa9\x02\n" +
	"\x1bUpdateOrderLifecycleRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12<\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x1d.trading.order.v1.OrderStatusR\tnewStatus\x12=\n" +
	"\ftriggered_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vtriggeredAt\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"M\n" +
	"\x1cUpdateOrderLifecycleResponse\x12-\n" +
	"\x05order\x18\x01 \x01(\v2\x17.trading.order.v1.OrderR\x05order\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"t\n" +
	"\x10GetOrderResponse\x12-\n" +
	"\x05order\x18\x01 \x01(\v2\x17.trading.order.v1.OrderR\x05order\x121\n" +
	"\x05fills\x18\x02 \x03(\v2\x1b.trading.order.v1.OrderFillR\x05fills\"\xb1\x01\n" +
	"\x15ListOrderFillsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12A\n" +
	"\x0eexecuted_after\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rexecutedAfter\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\fR\tpageToken\"s\n" +
	"\x16ListOrderFillsResponse\x121\n" +
	"\x05fills\x18\x01 \x03(\v2\x1b.trading.order.v1.OrderFillR\x05fills\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\fR\rnextPageToken\"\xaa\x0e\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vstrategy_id\x18\x02 \x01(\x05R\n" +
	"strategyId\x12G\n" +
	"\x11source_network_id\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\x0fsourceNetworkId\x12C\n" +
	"\x0fdest_network_id\x18\x04 \x01(\v2\x1b.google.protobuf.Int32ValueR\rdestNetworkId\x12\x1f\n" +
	"\vadapter_key\x18\x05 \x01(\tR\n" +
	"adapterKey\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12 \n" +
	"\fasset_in_ref\x18\a \x01(\tR\n" +
	"assetInRef\x12\"\n" +
	"\rasset_out_ref\x18\b \x01(\tR\vassetOutRef\x12/\n" +
	"\x04side\x18\t \x01(\x0e2\x1b.trading.order.v1.OrderSideR\x04side\x12/\n" +
	"\x04type\x18\n" +
	" \x01(\x0e2\x1b.trading.order.v1.OrderTypeR\x04type\x12/\n" +
	"\x03tif\x18\v \x01(\x0e2\x1d.trading.order.v1.TimeInForceR\x03tif\x12\x1f\n" +
	"\vreduce_only\x18\f \x01(\bR\n" +
	"reduceOnly\x12\x1b\n" +
	"\tpost_only\x18\r \x01(\bR\bpostOnly\x128\n" +
	"\bleverage\x18\x0e \x01(\v2\x1c.google.protobuf.StringValueR\bleverage\x12=\n" +
	"\vmargin_mode\x18\x0f \x01(\x0e2\x1c.trading.order.v1.MarginModeR\n" +
	"marginMode\x12\x1b\n" +
	"\tamount_in\x18\x10 \x01(\tR\bamountIn\x12B\n" +
	"\x0eamount_out_min\x18\x11 \x01(\v2\x1c.google.protobuf.StringValueR\famountOutMin\x12#\n" +
	"\rfilled_amount\x18\x12 \x01(\tR\ffilledAmount\x12=\n" +
	"\vlimit_price\x18\x13 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"limitPrice\x12;\n" +
	"\n" +
	"stop_price\x18\x14 \x01(\v2\x1c.google.protobuf.StringValueR\tstopPrice\x12J\n" +
	"\x12average_fill_price\x18\x15 \x01(\v2\x1c.google.protobuf.StringValueR\x10averageFillPrice\x12K\n" +
	"\x12slippage_tolerance\x18\x16 \x01(\v2\x1c.google.protobuf.StringValueR\x11slippageTolerance\x125\n" +
	"\x06status\x18\x17 \x01(\x0e2\x1d.trading.order.v1.OrderStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x18 \x01(\x03R\aversion\x12#\n" +
	"\revent_version\x18\x19 \x01(\x03R\feventVersion\x129\n" +
	"\n" +
	"created_at\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fsubmitted_at\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x125\n" +
	"\backed_at\x18\x1c \x01(\v2\x1a.google.protobuf.TimestampR\aackedAt\x129\n" +
	"\n" +
	"updated_at\x18\x1d \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\ftriggered_at\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\vtriggeredAt\x12=\n" +
	"\fcompleted_at\x18\x1f \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x129\n" +
	"\n" +
	"expired_at\x18  \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\x12;\n" +
	"\vcanceled_at\x18! \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"canceledAt\x12\x12\n" +
	"\x04tags\x18\" \x03(\tR\x04tags\x123\n" +
	"\bmetadata\x18# \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12L\n" +
	"\x15execution_preferences\x18$ \x01(\v2\x17.google.protobuf.StructR\x14executionPreferences\"\xda\x05\n" +
	"\tOrderFill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x1b\n" +
	"\tamount_in\x18\x04 \x01(\tR\bamountIn\x12\x1d\n" +
	"\n" +
	"amount_out\x18\x05 \x01(\tR\tamountOut\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12;\n" +
	"\n" +
	"fee_amount\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\tfeeAmount\x12@\n" +
	"\rfee_asset_ref\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\vfeeAssetRef\x12\x1f\n" +
	"\vadapter_key\x18\t \x01(\tR\n" +
	"adapterKey\x12\x17\n" +
	"\atx_hash\x18\n" +
	" \x01(\fR\x06txHash\x12>\n" +
	"\fblock_number\x18\v \x01(\v2\x1b.google.protobuf.Int64ValueR\vblockNumber\x128\n" +
	"\tlog_index\x18\f \x01(\v2\x1b.google.protobuf.Int32ValueR\blogIndex\x12;\n" +
	"\x06status\x18\r \x01(\x0e2#.trading.order.v1.TransactionStatusR\x06status\x12=\n" +
	"\fconfirmed_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAt\x12;\n" +
	"\vreverted_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"revertedAt\x12;\n" +
	"\vexecuted_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt*P\n" +
	"\tOrderSide\x12\x1a\n" +
	"\x16ORDER_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eORDER_SIDE_BUY\x10\x01\x12\x13\n" +
	"\x0fORDER_SIDE_SELL\x10\x02*\xe1\x01\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x01\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x02\x12\x13\n" +
	"\x0fORDER_TYPE_STOP\x10\x03\x12\x19\n" +
	"\x15ORDER_TYPE_STOP_LIMIT\x10\x04\x12\x13\n" +
	"\x0fORDER_TYPE_TWAP\x10\x05\x12\x12\n" +
	"\x0eORDER_TYPE_DCA\x10\x06\x12\x14\n" +
	"\x10ORDER_TYPE_SCALE\x10\a\x12\x1c\n" +
	"\x18ORDER_TYPE_TRAILING_STOP\x10\b*\x88\x01\n" +
	"\vTimeInForce\x12\x1d\n" +
	"\x19TIME_IN_FORCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TIME_IN_FORCE_GTC\x10\x01\x12\x15\n" +
	"\x11TIME_IN_FORCE_IOC\x10\x02\x12\x15\n" +
	"\x11TIME_IN_FORCE_FOK\x10\x03\x12\x15\n" +
	"\x11TIME_IN_FORCE_GTD\x10\x04*Z\n" +
	"\n" +
	"MarginMode\x12\x1b\n" +
	"\x17MARGIN_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MARGIN_MODE_CROSS\x10\x01\x12\x18\n" +
	"\x14MARGIN_MODE_ISOLATED\x10\x02*\xe9\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x15\n" +
	"\x11ORDER_STATUS_OPEN\x10\x02\x12!\n" +
	"\x1dORDER_STATUS_PARTIALLY_FILLED\x10\x03\x12\x17\n" +
	"\x13ORDER_STATUS_FILLED\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x05\x12\x19\n" +
	"\x15ORDER_STATUS_REJECTED\x10\x06\x12\x18\n" +
	"\x14ORDER_STATUS_EXPIRED\x10\a*\xb9\x01\n" +
	"\x11TransactionStatus\x12\"\n" +
	"\x1eTRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cTRANSACTION_STATUS_CONFIRMED\x10\x02\x12\x1d\n" +
	"\x19TRANSACTION_STATUS_FAILED\x10\x03\x12\x1f\n" +
	"\x1bTRANSACTION_STATUS_REVERTED\x10\x042\xf8\x03\n" +
	"\fOrderService\x12Z\n" +
	"\vCreateOrder\x12$.trading.order.v1.CreateOrderRequest\x1a%.trading.order.v1.CreateOrderResponse\x12]\n" +
	"\fAddOrderFill\x12%.trading.order.v1.AddOrderFillRequest\x1a&.trading.order.v1.AddOrderFillResponse\x12u\n" +
	"\x14UpdateOrderLifecycle\x12-.trading.order.v1.UpdateOrderLifecycleRequest\x1a..trading.order.v1.UpdateOrderLifecycleResponse\x12Q\n" +
	"\bGetOrder\x12!.trading.order.v1.GetOrderRequest\x1a\".trading.order.v1.GetOrderResponse\x12c\n" +
	"\x0eListOrderFills\x12'.trading.order.v1.ListOrderFillsRequest\x1a(.trading.order.v1.ListOrderFillsResponseBF\n" +
	"\x13com.trador.order.v1P\x01Z-order-gateway/pkg/pb/trading/order/v1;orderpbb\x06proto3"

var (
	file_trading_order_v1_order_service_proto_rawDescOnce sync.Once
	file_trading_order_v1_order_service_proto_rawDescData []byte
)

func file_trading_order_v1_order_service_proto_rawDescGZIP() []byte {
	file_trading_order_v1_order_service_proto_rawDescOnce.Do(func() {
		file_trading_order_v1_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trading_order_v1_order_service_proto_rawDesc), len(file_trading_order_v1_order_service_proto_rawDesc)))
	})
	return file_trading_order_v1_order_service_proto_rawDescData
}

var file_trading_order_v1_order_service_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_trading_order_v1_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_trading_order_v1_order_service_proto_goTypes = []any{
	(OrderSide)(0),                       // 0: trading.order.v1.OrderSide
	(OrderType)(0),                       // 1: trading.order.v1.OrderType
	(TimeInForce)(0),                     // 2: trading.order.v1.TimeInForce
	(MarginMode)(0),                      // 3: trading.order.v1.MarginMode
	(OrderStatus)(0),                     // 4: trading.order.v1.OrderStatus
	(TransactionStatus)(0),               // 5: trading.order.v1.TransactionStatus
	(*CreateOrderRequest)(nil),           // 6: trading.order.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),          // 7: trading.order.v1.CreateOrderResponse
	(*AddOrderFillRequest)(nil),          // 8: trading.order.v1.AddOrderFillRequest
	(*AddOrderFillResponse)(nil),         // 9: trading.order.v1.AddOrderFillResponse
	(*UpdateOrderLifecycleRequest)(nil),  // 10: trading.order.v1.UpdateOrderLifecycleRequest
	(*UpdateOrderLifecycleResponse)(nil), // 11: trading.order.v1.UpdateOrderLifecycleResponse
	(*GetOrderRequest)(nil),              // 12: trading.order.v1.GetOrderRequest
	(*GetOrderResponse)(nil),             // 13: trading.order.v1.GetOrderResponse
	(*ListOrderFillsRequest)(nil),        // 14: trading.order.v1.ListOrderFillsRequest
	(*ListOrderFillsResponse)(nil),       // 15: trading.order.v1.ListOrderFillsResponse
	(*Order)(nil),                        // 16: trading.order.v1.Order
	(*OrderFill)(nil),                    // 17: trading.order.v1.OrderFill
	(*wrapperspb.Int32Value)(nil),        // 18: google.protobuf.Int32Value
	(*wrapperspb.StringValue)(nil),       // 19: google.protobuf.StringValue
	(*structpb.Struct)(nil),              // 20: google.protobuf.Struct
	(*wrapperspb.Int64Value)(nil),        // 21: google.protobuf.Int64Value
	(*timestamppb.Timestamp)(nil),        // 22: google.protobuf.Timestamp
}
var file_trading_order_v1_order_service_proto_depIdxs = []int32{
	18, // 0: trading.order.v1.CreateOrderRequest.source_network_id:type_name -> google.protobuf.Int32Value
	18, // 1: trading.order.v1.CreateOrderRequest.dest_network_id:type_name -> google.protobuf.Int32Value
	0,  // 2: trading.order.v1.CreateOrderRequest.side:type_name -> trading.order.v1.OrderSide
	1,  // 3: trading.order.v1.CreateOrderRequest.type:type_name -> trading.order.v1.OrderType
	2,  // 4: trading.order.v1.CreateOrderRequest.tif:type_name -> trading.order.v1.TimeInForce
	3,  // 5: trading.order.v1.CreateOrderRequest.margin_mode:type_name -> trading.order.v1.MarginMode
	19, // 6: trading.order.v1.CreateOrderRequest.amount_out_min:type_name -> google.protobuf.StringValue
	19, // 7: trading.order.v1.CreateOrderRequest.limit_price:type_name -> google.protobuf.StringValue
	19, // 8: trading.order.v1.CreateOrderRequest.stop_price:type_name -> google.protobuf.StringValue
	19, // 9: trading.order.v1.CreateOrderRequest.slippage_tolerance:type_name -> google.protobuf.StringValue
	20, // 10: trading.order.v1.CreateOrderRequest.metadata:type_name -> google.protobuf.Struct
	20, // 11: trading.order.v1.CreateOrderRequest.execution_preferences:type_name -> google.protobuf.Struct
	16, // 12: trading.order.v1.CreateOrderResponse.order:type_name -> trading.order.v1.Order
	19, // 13: trading.order.v1.AddOrderFillRequest.fee_amount:type_name -> google.protobuf.StringValue
	19, // 14: trading.order.v1.AddOrderFillRequest.fee_asset_ref:type_name -> google.protobuf.StringValue
	19, // 15: trading.order.v1.AddOrderFillRequest.adapter_key:type_name -> google.protobuf.StringValue
	21, // 16: trading.order.v1.AddOrderFillRequest.block_number:type_name -> google.protobuf.Int64Value
	18, // 17: trading.order.v1.AddOrderFillRequest.log_index:type_name -> google.protobuf.Int32Value
	5,  // 18: trading.order.v1.AddOrderFillRequest.status:type_name -> trading.order.v1.TransactionStatus
	17, // 19: trading.order.v1.AddOrderFillResponse.fill:type_name -> trading.order.v1.OrderFill
	16, // 20: trading.order.v1.AddOrderFillResponse.order:type_name -> trading.order.v1.Order
	4,  // 21: trading.order.v1.UpdateOrderLifecycleRequest.new_status:type_name -> trading.order.v1.OrderStatus
	22, // 22: trading.order.v1.UpdateOrderLifecycleRequest.triggered_at:type_name -> google.protobuf.Timestamp
	22, // 23: trading.order.v1.UpdateOrderLifecycleRequest.completed_at:type_name -> google.protobuf.Timestamp
	20, // 24: trading.order.v1.UpdateOrderLifecycleRequest.metadata:type_name -> google.protobuf.Struct
	16, // 25: trading.order.v1.UpdateOrderLifecycleResponse.order:type_name -> trading.order.v1.Order
	16, // 26: trading.order.v1.GetOrderResponse.order:type_name -> trading.order.v1.Order
	17, // 27: trading.order.v1.GetOrderResponse.fills:type_name -> trading.order.v1.OrderFill
	22, // 28: trading.order.v1.ListOrderFillsRequest.executed_after:type_name -> google.protobuf.Timestamp
	17, // 29: trading.order.v1.ListOrderFillsResponse.fills:type_name -> trading.order.v1.OrderFill
	18, // 30: trading.order.v1.Order.source_network_id:type_name -> google.protobuf.Int32Value
	18, // 31: trading.order.v1.Order.dest_network_id:type_name -> google.protobuf.Int32Value
	0,  // 32: trading.order.v1.Order.side:type_name -> trading.order.v1.OrderSide
	1,  // 33: trading.order.v1.Order.type:type_name -> trading.order.v1.OrderType
	2,  // 34: trading.order.v1.Order.tif:type_name -> trading.order.v1.TimeInForce
	19, // 35: trading.order.v1.Order.leverage:type_name -> google.protobuf.StringValue
	3,  // 36: trading.order.v1.Order.margin_mode:type_name -> trading.order.v1.MarginMode
	19, // 37: trading.order.v1.Order.amount_out_min:type_name -> google.protobuf.StringValue
	19, // 38: trading.order.v1.Order.limit_price:type_name -> google.protobuf.StringValue
	19, // 39: trading.order.v1.Order.stop_price:type_name -> google.protobuf.StringValue
	19, // 40: trading.order.v1.Order.average_fill_price:type_name -> google.protobuf.StringValue
	19, // 41: trading.order.v1.Order.slippage_tolerance:type_name -> google.protobuf.StringValue
	4,  // 42: trading.order.v1.Order.status:type_name -> trading.order.v1.OrderStatus
	22, // 43: trading.order.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	22, // 44: trading.order.v1.Order.submitted_at:type_name -> google.protobuf.Timestamp
	22, // 45: trading.order.v1.Order.acked_at:type_name -> google.protobuf.Timestamp
	22, // 46: trading.order.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	22, // 47: trading.order.v1.Order.triggered_at:type_name -> google.protobuf.Timestamp
	22, // 48: trading.order.v1.Order.completed_at:type_name -> google.protobuf.Timestamp
	22, // 49: trading.order.v1.Order.expired_at:type_name -> google.protobuf.Timestamp
	22, // 50: trading.order.v1.Order.canceled_at:type_name -> google.protobuf.Timestamp
	20, // 51: trading.order.v1.Order.metadata:type_name -> google.protobuf.Struct
	20, // 52: trading.order.v1.Order.execution_preferences:type_name -> google.protobuf.Struct
	19, // 53: trading.order.v1.OrderFill.fee_amount:type_name -> google.protobuf.StringValue
	19, // 54: trading.order.v1.OrderFill.fee_asset_ref:type_name -> google.protobuf.StringValue
	21, // 55: trading.order.v1.OrderFill.block_number:type_name -> google.protobuf.Int64Value
	18, // 56: trading.order.v1.OrderFill.log_index:type_name -> google.protobuf.Int32Value
	5,  // 57: trading.order.v1.OrderFill.status:type_name -> trading.order.v1.TransactionStatus
	22, // 58: trading.order.v1.OrderFill.confirmed_at:type_name -> google.protobuf.Timestamp
	22, // 59: trading.order.v1.OrderFill.reverted_at:type_name -> google.protobuf.Timestamp
	22, // 60: trading.order.v1.OrderFill.executed_at:type_name -> google.protobuf.Timestamp
	6,  // 61: trading.order.v1.OrderService.CreateOrder:input_type -> trading.order.v1.CreateOrderRequest
	8,  // 62: trading.order.v1.OrderService.AddOrderFill:input_type -> trading.order.v1.AddOrderFillRequest
	10, // 63: trading.order.v1.OrderService.UpdateOrderLifecycle:input_type -> trading.order.v1.UpdateOrderLifecycleRequest
	12, // 64: trading.order.v1.OrderService.GetOrder:input_type -> trading.order.v1.GetOrderRequest
	14, // 65: trading.order.v1.OrderService.ListOrderFills:input_type -> trading.order.v1.ListOrderFillsRequest
	7,  // 66: trading.order.v1.OrderService.CreateOrder:output_type -> trading.order.v1.CreateOrderResponse
	9,  // 67: trading.order.v1.OrderService.AddOrderFill:output_type -> trading.order.v1.AddOrderFillResponse
	11, // 68: trading.order.v1.OrderService.UpdateOrderLifecycle:output_type -> trading.order.v1.UpdateOrderLifecycleResponse
	13, // 69: trading.order.v1.OrderService.GetOrder:output_type -> trading.order.v1.GetOrderResponse
	15, // 70: trading.order.v1.OrderService.ListOrderFills:output_type -> trading.order.v1.ListOrderFillsResponse
	66, // [66:71] is the sub-list for method output_type
	61, // [61:66] is the sub-list for method input_type
	61, // [61:61] is the sub-list for extension type_name
	61, // [61:61] is the sub-list for extension extendee
	0,  // [0:61] is the sub-list for field type_name
}

func init() { file_trading_order_v1_order_service_proto_init() }
func file_trading_order_v1_order_service_proto_init() {
	if File_trading_order_v1_order_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_order_v1_order_service_proto_rawDesc), len(file_trading_order_v1_order_service_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trading_order_v1_order_service_proto_goTypes,
		DependencyIndexes: file_trading_order_v1_order_service_proto_depIdxs,
		EnumInfos:         file_trading_order_v1_order_service_proto_enumTypes,
		MessageInfos:      file_trading_order_v1_order_service_proto_msgTypes,
	}.Build()
	File_trading_order_v1_order_service_proto = out.File
	file_trading_order_v1_order_service_proto_goTypes = nil
	file_trading_order_v1_order_service_proto_depIdxs = nil
}
