// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: trading/order/v1/order_service.proto

package orderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderService_CreateOrder_FullMethodName          = "/trading.order.v1.OrderService/CreateOrder"
	OrderService_AddOrderFill_FullMethodName         = "/trading.order.v1.OrderService/AddOrderFill"
	OrderService_UpdateOrderLifecycle_FullMethodName = "/trading.order.v1.OrderService/UpdateOrderLifecycle"
	OrderService_GetOrder_FullMethodName             = "/trading.order.v1.OrderService/GetOrder"
	OrderService_ListOrderFills_FullMethodName       = "/trading.order.v1.OrderService/ListOrderFills"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrderService defines the gRPC boundary for the canonical order database.
type OrderServiceClient interface {
	// CreateOrder issues a new order and persists it via api.create_order.
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	// AddOrderFill records a venue fill and updates order aggregates via api.add_order_fill.
	AddOrderFill(ctx context.Context, in *AddOrderFillRequest, opts ...grpc.CallOption) (*AddOrderFillResponse, error)
	// UpdateOrderLifecycle advances an order through its lifecycle using api.update_order_lifecycle.
	UpdateOrderLifecycle(ctx context.Context, in *UpdateOrderLifecycleRequest, opts ...grpc.CallOption) (*UpdateOrderLifecycleResponse, error)
	// GetOrder retrieves the latest order snapshot.
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	// ListOrderFills streams fills for a specific order in executed_at order.
	ListOrderFills(ctx context.Context, in *ListOrderFillsRequest, opts ...grpc.CallOption) (*ListOrderFillsResponse, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, OrderService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) AddOrderFill(ctx context.Context, in *AddOrderFillRequest, opts ...grpc.CallOption) (*AddOrderFillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddOrderFillResponse)
	err := c.cc.Invoke(ctx, OrderService_AddOrderFill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateOrderLifecycle(ctx context.Context, in *UpdateOrderLifecycleRequest, opts ...grpc.CallOption) (*UpdateOrderLifecycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrderLifecycleResponse)
	err := c.cc.Invoke(ctx, OrderService_UpdateOrderLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, OrderService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListOrderFills(ctx context.Context, in *ListOrderFillsRequest, opts ...grpc.CallOption) (*ListOrderFillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrderFillsResponse)
	err := c.cc.Invoke(ctx, OrderService_ListOrderFills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility.
//
// OrderService defines the gRPC boundary for the canonical order database.
type OrderServiceServer interface {
	// CreateOrder issues a new order and persists it via api.create_order.
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	// AddOrderFill records a venue fill and updates order aggregates via api.add_order_fill.
	AddOrderFill(context.Context, *AddOrderFillRequest) (*AddOrderFillResponse, error)
	// UpdateOrderLifecycle advances an order through its lifecycle using api.update_order_lifecycle.
	UpdateOrderLifecycle(context.Context, *UpdateOrderLifecycleRequest) (*UpdateOrderLifecycleResponse, error)
	// GetOrder retrieves the latest order snapshot.
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	// ListOrderFills streams fills for a specific order in executed_at order.
	ListOrderFills(context.Context, *ListOrderFillsRequest) (*ListOrderFillsResponse, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceServer struct{}

func (UnimplementedOrderServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderServiceServer) AddOrderFill(context.Context, *AddOrderFillRequest) (*AddOrderFillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrderFill not implemented")
}
func (UnimplementedOrderServiceServer) UpdateOrderLifecycle(context.Context, *UpdateOrderLifecycleRequest) (*UpdateOrderLifecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderLifecycle not implemented")
}
func (UnimplementedOrderServiceServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrderServiceServer) ListOrderFills(context.Context, *ListOrderFillsRequest) (*ListOrderFillsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrderFills not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}
func (UnimplementedOrderServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_AddOrderFill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrderFillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).AddOrderFill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_AddOrderFill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).AddOrderFill(ctx, req.(*AddOrderFillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_UpdateOrderLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).UpdateOrderLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_UpdateOrderLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).UpdateOrderLifecycle(ctx, req.(*UpdateOrderLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListOrderFills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrderFillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListOrderFills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListOrderFills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListOrderFills(ctx, req.(*ListOrderFillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trading.order.v1.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "AddOrderFill",
			Handler:    _OrderService_AddOrderFill_Handler,
		},
		{
			MethodName: "UpdateOrderLifecycle",
			Handler:    _OrderService_UpdateOrderLifecycle_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _OrderService_GetOrder_Handler,
		},
		{
			MethodName: "ListOrderFills",
			Handler:    _OrderService_ListOrderFills_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trading/order/v1/order_service.proto",
}
